	LIST	P=PIC16F648A
	INCLUDE	<P16F648A.INC>
	__CONFIG 	_CP_OFF & _MCLRE_OFF & _PWRTE_OFF & _WDT_OFF & _HS_OSC & _LVP_OFF & _BOREN_OFF
	
; ALL BANK
TEMP0		EQU		H'70'
TEMP1		EQU		H'71'
GUN_Y		EQU		H'72'
GUN_X		EQU		H'73'
GUN_FLAGS	EQU		H'74'

		ORG		H'0000'
INIT		
		MOVLW		H'07'
		MOVWF		CMCON
		BSF		STATUS,RP0
		CLRF		TRISA
		MOVLW		B'00000110'
		MOVWF		TRISB
		
		BCF		STATUS, RP0
		CLRF		PORTA
		CLRF		PORTB
		
		BSF		RCSTA, SPEN
		BSF		STATUS, RP0
		BCF		TXSTA, SYNC
		BSF		TXSTA, TXEN
		BCF		STATUS, RP0
		BSF		RCSTA, CREN
		
		GOTO		START
START	
		BSF		STATUS, RP0
		BCF		TXSTA, BRGH
		MOVLW		D'129'
		MOVWF		SPBRG
		BCF		STATUS, RP0
		BTFSS		PIR1, RCIF
		GOTO		$ - 1
		MOVFW		RCREG
		MOVWF		TEMP0
		MOVLW		B'11000000'
		ANDWF		TEMP0, W
		MOVWF		TEMP1
		BCF		STATUS, C
		RLF		TEMP1, F
		RLF		TEMP1, F
		RLF		TEMP1, F
		MOVLW		GUN_Y
		MOVWF		FSR
		MOVFW		TEMP1
		ADDWF		FSR, F
		MOVFW		TEMP0
		MOVWF		INDF
		MOVLW		H'02'
		SUBWF		TEMP1, W
		BTFSS		STATUS, Z
		GOTO		START
		BSF		STATUS, RP0
		BSF		TXSTA, BRGH
		CLRF		SPBRG
		BCF		STATUS, RP0
		MOVFW		GUN_Y
		MOVWF		TXREG
		MOVFW		GUN_X
		MOVWF		TXREG
		BSF		STATUS, RP0
		BTFSS		TXSTA, TRMT
		GOTO		$ - 1
		BCF		STATUS, RP0
		MOVFW		GUN_FLAGS
		MOVWF		TXREG
		BSF		STATUS, RP0
		BTFSS		TXSTA, TRMT
		GOTO		$ - 1
		BCF		STATUS, RP0
		GOTO		START
		
		END
