	LIST	P=PIC16F648A
	INCLUDE	<P16F648A.INC>
	__CONFIG 	_CP_OFF & _MCLRE_OFF & _PWRTE_OFF & _WDT_OFF & _HS_OSC & _LVP_OFF & _BOREN_OFF
	
; ALL BANK
TEMP0		EQU		H'70'

		ORG		H'0000'
INIT		
		MOVLW		H'07'
		MOVWF		CMCON
		BSF		STATUS,RP0
		CLRF		TRISA
		MOVLW		B'00000110'
		MOVWF		TRISB
		
		BCF		STATUS, RP0
		CLRF		PORTA
		CLRF		PORTB
		
		BSF		RCSTA, SPEN
		BSF		STATUS, RP0
		BCF		TXSTA, SYNC
		BSF		TXSTA, TXEN
		BCF		STATUS, RP0
		BSF		RCSTA, CREN
		
		GOTO		START
START	
		BSF		STATUS, RP0
		BCF		TXSTA, BRGH
		MOVLW		D'129'
		MOVWF		SPBRG
		BCF		STATUS, RP0
		BTFSS		PIR1, RCIF
		GOTO		$ - 1
		MOVFW		RCREG
		MOVWF		TEMP0
		BSF		STATUS, RP0
		BSF		TXSTA, BRGH
		CLRF		SPBRG
		BCF		STATUS, RP0
		MOVFW		TEMP0
		MOVWF		TXREG
		BSF		STATUS, RP0
		BTFSS		TXSTA, TRMT
		GOTO		$ - 1
		BCF		STATUS, RP0
		GOTO		START
		
		END
