	LIST	P=PIC16F648A
	INCLUDE	<P16F648A.INC>
	__CONFIG 	_CP_OFF & _MCLRE_OFF & _PWRTE_OFF & _WDT_OFF & _HS_OSC & _LVP_OFF & _BOREN_OFF    

; Pin definitions
;PORTB
MASTER_BUSY	EQU		H'05'
	
; ALL BANK
ARG0		EQU		H'70'
ARG1		EQU		H'71'
TEMP0		EQU		H'72'
TEMP1		EQU		H'73'

		ORG		H'0000'
INIT		
		MOVLW		H'07'
		MOVWF		CMCON
		BSF		STATUS,RP0	;Set Bank 1
		CLRF		TRISA		;Set RA7-5 to Output and RA4-0 to Input 
		MOVLW		B'00000110'
		MOVWF		TRISB		;Set Port-B to all Output
		MOVLW		H'3F'
		MOVWF		PR2
		
		BCF		STATUS,RP0	;Set Bank 0
		MOVLW		B'00000001'
		MOVWF		PORTA
		MOVLW		B'00100000'
		MOVWF		PORTB
		
		MOVLW		B'00001100'
		IORWF		CCP1CON
		
		BSF		T2CON, TMR2ON
		MOVLW		H'0F'
		MOVWF		CCPR1L
		
		MOVLW		B'11000000'
		IORWF		INTCON, F
		
		BSF		RCSTA, SPEN
		BSF		RCSTA, CREN
		BSF		STATUS, RP0
		BCF		TXSTA, SYNC
		CLRF		SPBRG
		BSF		TXSTA, TXEN
		
		BCF		STATUS, RP0
		
		GOTO		START

SEND_COMMAND	; ARG0: address, ARG1: command
		BTFSS		PIR1, RCIF
		GOTO		$ - 1
		BCF		RCSTA, CREN
		MOVFW		RCREG
		MOVFW		RCREG
		BSF		STATUS, RP0
		BTFSS		TXSTA, TRMT
		GOTO		$ - 1
		BCF		STATUS, RP0
		BCF		PORTB, MASTER_BUSY
		MOVFW		ARG0
		MOVWF		TXREG
		MOVFW		ARG1
		MOVWF		TXREG
		BSF		PORTB, MASTER_BUSY
		BSF		RCSTA, CREN
		RETURN
		
START
		MOVLW		H'00'
		MOVWF		ARG0
		MOVLW		H'01'
		MOVWF		ARG1
		CALL		SEND_COMMAND
		
		GOTO		START

NOP10CYCLES	NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		RETURN
		
		END
