	LIST	P=PIC16F648A
	INCLUDE	<P16F648A.INC>
	__CONFIG 	_CP_OFF & _MCLRE_OFF & _PWRTE_OFF & _WDT_OFF & _HS_OSC & _LVP_OFF & _BOREN_OFF    

; Constants
CAMERA_ADDRESS	EQU		H'58'
	
; Pin definitions
I2C_SCL		EQU		H'03'
I2C_SDA		EQU		H'04'
	
; ALL BANK
ARG0		EQU		H'70'
ARG1		EQU		H'71'
TEMP0		EQU		H'72'
TEMP1		EQU		H'73'
GUN_Y		EQU		H'74'
GUN_X		EQU		H'75'
GUN_FLAGS	EQU		H'76'
IR_POINT0_X	EQU		H'77'
IR_POINT0_Y	EQU		H'78'
IR_POINT1_X	EQU		H'79'
IR_POINT1_Y	EQU		H'7A'
TEMP2		EQU		H'7B'
IR_POINT2_X	EQU		H'7C'
IR_POINT2_Y	EQU		H'7D'
IR_POINT3_X	EQU		H'7E'
IR_POINT3_Y	EQU		H'7F'

		ORG		H'0000'
INIT		
		MOVLW		H'07'
		MOVWF		CMCON
		BSF		STATUS,RP0	;Set Bank 1
		CLRF		TRISA		;Set RA7-5 to Output and RA4-0 to Input 
		MOVLW		B'11110110'
		MOVWF		TRISB		;Set Port-B to all Output
		MOVLW		D'131'
		MOVWF		PR2

		MOVLW		B'01111111'
		MOVWF		OPTION_REG
		
		BCF		STATUS,RP0	;Set Bank 0
		MOVLW		B'00000001'
		MOVWF		PORTA
		CLRF		PORTB
		
		MOVLW		B'00010001'
		MOVWF		T1CON
		
		MOVLW		B'00111100'
		IORWF		CCP1CON
		MOVLW		B'00111111'
		MOVWF		CCPR1L
		BSF		T2CON, TMR2ON
		
		BSF		RCSTA, SPEN
		BSF		STATUS, RP0
		BCF		TXSTA, SYNC
		MOVLW		D'129'
		MOVWF		SPBRG
		
		
		CLRF		SPBRG
		
		
		BSF		TXSTA, TXEN
		BCF		STATUS, RP0
		
		CALL		INIT_CAMERA
		
		CLRF		GUN_Y
		CLRF		GUN_X
		CLRF		GUN_FLAGS
		
		GOTO		START
		
I2C_SCL_LOW
		BCF		PORTA, I2C_SCL
		CALL		NOP10CYCLES
		RETURN

I2C_SCL_HIGH
		BSF		PORTA, I2C_SCL
		CALL		NOP10CYCLES
		RETURN
		
I2C_SCL_INPUT
		BSF		STATUS, RP0
		BSF		TRISA, I2C_SCL
		BCF		STATUS, RP0
		RETURN
		
I2C_SCL_OUTPUT
		BSF		STATUS, RP0
		BCF		TRISA, I2C_SCL
		BCF		STATUS, RP0
		RETURN
		
I2C_SDA_LOW
		BCF		PORTA, I2C_SDA
		CALL		NOP10CYCLES
		RETURN

I2C_SDA_HIGH
		BSF		PORTA, I2C_SDA
		CALL		NOP10CYCLES
		RETURN
		
I2C_SDA_INPUT
		BSF		STATUS, RP0
		BSF		TRISA, I2C_SDA
		BCF		STATUS, RP0
		RETURN
		
I2C_SDA_OUTPUT
		BSF		STATUS, RP0
		BCF		TRISA, I2C_SDA
		BCF		STATUS, RP0
		RETURN
		
I2C_START_CONDITION
		CALL		I2C_SDA_LOW
		CALL		I2C_SCL_LOW
		RETURN
		
I2C_STOP_CONDITION
		CALL		I2C_SCL_HIGH
		CALL		I2C_SDA_HIGH
		RETURN
		
I2C_SEND_DATA
		MOVWF		TEMP0
		MOVLW		H'08'
		MOVWF		TEMP1
I2C_SEND_DATA_LOOP
		BTFSC		TEMP0, 7
		GOTO		I2C_SEND_DATA_LOOP_SDA_1
		CALL		I2C_SDA_LOW
		GOTO		I2C_SEND_DATA_LOOP_SDA_END
I2C_SEND_DATA_LOOP_SDA_1
		CALL		I2C_SDA_HIGH
I2C_SEND_DATA_LOOP_SDA_END
		RLF		TEMP0, F
		CALL		I2C_SCL_HIGH
		CALL		I2C_SCL_LOW
		DECFSZ		TEMP1, F
		GOTO		I2C_SEND_DATA_LOOP
		CALL		I2C_SDA_HIGH
		CALL		I2C_SDA_INPUT
		CALL		I2C_SCL_HIGH
		BTFSC		PORTA, I2C_SDA
		GOTO		I2C_SEND_DATA_SUCCESS
		CALL		I2C_SCL_LOW
		CALL		I2C_SDA_OUTPUT
		CALL		I2C_SDA_LOW
		RETLW		H'01'
I2C_SEND_DATA_SUCCESS
		CALL		I2C_SCL_LOW
		CALL		I2C_SDA_OUTPUT
		CALL		I2C_SDA_LOW
		CALL		I2C_SCL_INPUT
		BTFSS		PORTA, I2C_SCL
		GOTO		$ - 1
		CALL		I2C_SCL_OUTPUT
		CALL		I2C_SCL_LOW
		RETLW		H'00'
		
I2C_READ_DATA
		CLRF		TEMP0
		CALL		I2C_SDA_INPUT
		MOVLW		H'08'
		MOVWF		TEMP1
I2C_READ_DATA_LOOP
		RLF		TEMP0, F
		CALL		I2C_SCL_HIGH
		BTFSC		PORTA, I2C_SDA
		BSF		TEMP0, 0
		CALL		I2C_SCL_LOW
		DECFSZ		TEMP1, F
		GOTO		I2C_READ_DATA_LOOP
		CALL		I2C_SDA_OUTPUT
		CALL		I2C_SDA_LOW
		CALL		I2C_SCL_HIGH
		CALL		I2C_SCL_LOW
		MOVFW		TEMP0
		RETURN
	
WRITE_CAMERA	; ARG0: Address, ARG1: data
		CALL		I2C_START_CONDITION
		MOVLW		CAMERA_ADDRESS << 1
		CALL		I2C_SEND_DATA
		ADDLW		H'00'
		BTFSC		STATUS, Z
		GOTO		WRITE_CAMERA_FAIL
		MOVFW		ARG0
		CALL		I2C_SEND_DATA
		ADDLW		H'00'
		BTFSC		STATUS, Z
		GOTO		WRITE_CAMERA_FAIL
		MOVFW		ARG1
		CALL		I2C_SEND_DATA
		ADDLW		H'00'
		BTFSC		STATUS, Z
		GOTO		WRITE_CAMERA_FAIL
		CALL		I2C_STOP_CONDITION		
		RETURN
WRITE_CAMERA_FAIL
		CALL		I2C_STOP_CONDITION
		GOTO		WRITE_CAMERA		

READ_CAMERA
		CALL		I2C_START_CONDITION
		MOVLW		CAMERA_ADDRESS << 1
		CALL		I2C_SEND_DATA
		ADDLW		H'00'
		BTFSC		STATUS, Z
		GOTO		READ_CAMERA_FAIL
		MOVLW		H'36'
		CALL		I2C_SEND_DATA
		ADDLW		H'00'
		BTFSC		STATUS, Z
		GOTO		READ_CAMERA_FAIL
		CALL		I2C_STOP_CONDITION
		
		CALL		I2C_START_CONDITION
		MOVLW		CAMERA_ADDRESS << 1 | 1
		CALL		I2C_SEND_DATA
		ADDLW		H'00'
		BTFSC		STATUS, Z
		GOTO		READ_CAMERA_FAIL
		CALL		I2C_READ_DATA
		MOVLW		IR_POINT0_X
		CALL		READ_ONE_POINT
		MOVLW		IR_POINT1_X
		CALL		READ_ONE_POINT
		MOVLW		IR_POINT2_X
		CALL		READ_ONE_POINT
		MOVLW		IR_POINT3_X
		CALL		READ_ONE_POINT
		CALL		I2C_READ_DATA
		CALL		I2C_READ_DATA
		CALL		I2C_STOP_CONDITION		
		RETURN
READ_CAMERA_FAIL
		CALL		I2C_STOP_CONDITION
		GOTO		READ_CAMERA		
		
INIT_CAMERA
		MOVLW		H'30'
		MOVWF		ARG0
		MOVLW		H'01'
		MOVWF		ARG1
		CALL		WRITE_CAMERA
		
		MOVLW		H'30'
		MOVWF		ARG0
		MOVLW		H'08'
		MOVWF		ARG1
		CALL		WRITE_CAMERA
		
		MOVLW		H'06'
		MOVWF		ARG0
		MOVLW		H'90'
		MOVWF		ARG1
		CALL		WRITE_CAMERA
		
		MOVLW		H'08'
		MOVWF		ARG0
		MOVLW		H'C0'
		MOVWF		ARG1
		CALL		WRITE_CAMERA
		
		MOVLW		H'1A'
		MOVWF		ARG0
		MOVLW		H'40'
		MOVWF		ARG1
		CALL		WRITE_CAMERA
		
		MOVLW		H'33'
		MOVWF		ARG0
		MOVLW		H'33'
		MOVWF		ARG1
		CALL		WRITE_CAMERA
		
		RETURN
	
READ_ONE_POINT
		MOVWF		FSR
		CALL		I2C_READ_DATA
		MOVWF		INDF
		BCF		STATUS, C
		RRF		INDF, F
		RRF		INDF, F
		RRF		INDF, F
		MOVLW		B'00011111'
		ANDWF		INDF, F
		CALL		I2C_READ_DATA
		CALL		I2C_READ_DATA
		MOVWF		TEMP0
		BCF		STATUS, C
		RLF		TEMP0, F
		MOVLW		B'01100000'
		ANDWF		TEMP0, W
		IORWF		INDF, F
		RETURN

IR_SEND
		MOVWF		TXREG
		BSF		STATUS, RP0
		BTFSS		TXSTA, TRMT
		GOTO		$ - 1
		BCF		STATUS, RP0
		RETURN

IR_COOLDOWN
		CLRF		TMR1H
		CLRF		TMR1L
		BCF		PIR1, TMR1IF
		BTFSS		PIR1, TMR1IF
		GOTO		$ - 1
		RETURN

START	
		CALL		READ_CAMERA
		;MOVFW		IR_POINT0_X
		;MOVWF		TXREG
		;MOVFW		IR_POINT1_X
		;MOVWF		TXREG
		;BSF		STATUS, RP0
		;BTFSS		TXSTA, TRMT
		;GOTO		$ - 1
		;BCF		STATUS, RP0
		;MOVFW		IR_POINT2_X
		;MOVWF		TXREG
		;MOVFW		IR_POINT3_X
		;MOVWF		TXREG
		;GOTO		START
		
		MOVLW		H'03'
		MOVWF		TEMP0
		MOVFW		IR_POINT0_X
		MOVWF		TEMP1
		MOVWF		TEMP2
LOOP0
		MOVLW		IR_POINT0_X
		MOVWF		FSR
		MOVFW		TEMP0
		ADDWF		FSR, F
		
		MOVLW		B'01111111'
		SUBWF		INDF, W
		BTFSC		STATUS, Z
		GOTO		LOOP0_END
		
		MOVFW		TEMP1
		SUBWF		INDF, W
		MOVFW		INDF
		BTFSS		STATUS, C
		MOVWF		TEMP1
		
		MOVFW		INDF
		SUBWF		TEMP2, W
		MOVFW		INDF
		BTFSS		STATUS, C
		MOVWF		TEMP2
LOOP0_END
		DECFSZ		TEMP0
		GOTO		LOOP0
		
		MOVFW		TEMP1
		MOVWF		IR_POINT0_X
		
		MOVWF		TXREG
		
		MOVFW		TEMP2
		MOVWF		IR_POINT1_X
		
		MOVWF		TXREG
		
		GOTO		START
		
		;BTFSC		PORTB, 4
		;GOTO		$ + 6
		;INCF		GUN_Y, F
		;MOVLW		D'42'
		;SUBWF		GUN_Y, W
		;BTFSC		STATUS, Z
		;CLRF		GUN_Y
		
		;BTFSC		PORTB, 5
		;GOTO		$ + 5
		;DECF		GUN_Y, F
		;MOVLW		D'42'
		;BTFSC		GUN_Y, 7
		;MOVWF		GUN_Y
		
		MOVFW		IR_POINT0_X
		MOVWF		GUN_X
		MOVFW		IR_POINT1_X
		ADDWF		GUN_X, F
		BCF		STATUS, C
		RRF		GUN_X, F
		
		
		MOVFW		IR_POINT0_X
		MOVWF		TXREG
		MOVFW		IR_POINT1_X
		MOVWF		TXREG
		BSF		STATUS, RP0
		BTFSS		TXSTA, TRMT
		BCF		STATUS, RP0
		MOVFW		GUN_X
		MOVWF		TXREG
		GOTO		START
		
		MOVLW		B'00111111'
		SUBWF		GUN_X, W
		SUBLW		H'00'
		ADDLW		B'00111111'
		MOVWF		GUN_X
		
		BCF		STATUS, C
		RRF		GUN_X, F
		RRF		GUN_X, F
		
		;BTFSC		PORTB, 6
		;GOTO		$ + 6
		;INCF		GUN_X, F
		MOVLW		D'27'
		SUBWF		GUN_X, W
		MOVLW		D'27'
		BTFSC		STATUS, C
		MOVWF		GUN_X
		
		;BTFSC		PORTB, 7
		;GOTO		$ + 5
		;DECF		GUN_X, F
		BTFSC		GUN_X, 7
		CLRF		GUN_X
		
		
		;MOVFW		GUN_X
		;MOVWF		TXREG
		;GOTO		START
		
		;BSF		STATUS, C
		;MOVLW		D'129'
		;MOVWF		SPBRG
		;BCF		STATUS, C
		
		
		MOVFW		GUN_Y
		ANDLW		B'00111111'
		CALL		IR_SEND
		MOVFW		GUN_X
		ANDLW		B'00111111'
		IORLW		B'01000000'
		CALL		IR_SEND
		MOVFW		GUN_FLAGS
		ANDLW		B'00111111'
		IORLW		B'10000000'
		CALL		IR_SEND
		CALL		IR_COOLDOWN
		GOTO		START
		
;Subroutine for waiting 10-micro-second		;0.25-micro*4-Clock*(2+8)-Cycle=10-micro
NOP10CYCLES	NOP				;1-Cycle
		NOP				;1-Cycle
		NOP				;1-Cycle
		NOP				;1-Cycle
		NOP				;1-Cycle
		NOP				;1-Cycle
		RETURN				;2-Cycle  Total 8-Cycle
		
		END
