	LIST	P=PIC16F648A
	INCLUDE	<P16F648A.INC>
	__CONFIG 	_CP_OFF & _MCLRE_OFF & _PWRTE_OFF & _WDT_OFF & _HS_OSC & _LVP_OFF & _BOREN_OFF    

; ALL BANK
TEMP0		EQU		H'37'

;Program Start
		ORG		H'0000'		;Reset Start
INIT		CLRF		PORTA
		MOVLW		H'07'
		MOVWF		CMCON
		BSF		STATUS,RP0	;Set Bank 1
		MOVLW		B'00100000'
		MOVWF		TRISA		;Set RA7-5 to Output and RA4-0 to Input 
		CLRF		TRISB		;Set Port-B to all Output
		MOVLW		H'3F'
		MOVWF		PR2
		
		BCF		STATUS,RP0	;Set Bank 0
		MOVLW		B'00000001'
		MOVWF		PORTA
		CLRF		PORTB
		
		MOVLW		B'00001100'
		IORWF		CCP1CON
		
		BSF		T2CON, TMR2ON
		;MOVLW		H'0F'
		MOVLW		H'00'
		MOVWF		CCPR1L
		;GOTO		$
		
		MOVLW		B'11000000'
		IORWF		INTCON, F
		
		BSF		RCSTA, SPEN
		BSF		STATUS, RP0
		BSF		TRISB, 1
		BSF		TRISB, 2
		BCF		TXSTA, SYNC
		MOVLW		D'207'
		MOVWF		SPBRG
		BSF		TXSTA, TXEN
		BCF		STATUS, RP0

HSYNC_TYPE_VSYNCSTART	EQU	H'00'
HSYNC_TYPE_VSYNCEND	EQU	H'01'
HSYNC_TYPE_CALIB	EQU	H'02'
HSYNC_TYPE_DRAW	EQU	H'03'
HSYNC_TYPE_END	EQU	H'04'
HSYNC		MACRO		TYPE	; Wait 14 instructions after SYNC.
	variable	I
	IF	TYPE == HSYNC_TYPE_VSYNCSTART
		MOVLW		B'0000011'
		XORWF		PORTA, F
	ELSE
		BSF		PORTA, 1
		NOP
	ENDIF
		NOP
		NOP
		NOP
		MOVLW		H'00'
I = 0
	IF	TYPE == HSYNC_TYPE_DRAW
	WHILE	I < D'45'
		MOVWF		PORTB
		ADDLW		H'10'
I += 1
	ENDW
	CLRF		PORTB
	ELSE
	WHILE	I < D'09'
		CALL		TIME10MICRO
I += 1
	ENDW
		NOP
	ENDIF
		NOP
	IF	TYPE == HSYNC_TYPE_VSYNCEND
		MOVLW		B'00000011'
		XORWF		PORTA, F
	ELSE
		NOP
		BCF		PORTA, 1
	ENDIF
		ENDM

REPEAT_HSYNC	MACRO		COUNT, TYPE
		LOCAL		LOOP, NOT_ZERO, ZERO
		MOVLW		COUNT
		MOVWF		TEMP0
LOOP:		HSYNC		TYPE
		DECFSZ		TEMP0, F
		GOTO		NOT_ZERO
		GOTO		ZERO
NOT_ZERO:	NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		GOTO		LOOP
ZERO:		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		ENDM

DRAW_DISPLAY
		HSYNC		HSYNC_TYPE_VSYNCSTART
		CALL		TIME10MICRO
		NOP
		NOP
		NOP
		NOP
		HSYNC		HSYNC_TYPE_VSYNCEND
		NOP
		NOP
		REPEAT_HSYNC	D'33', HSYNC_TYPE_CALIB
		NOP
		NOP
		REPEAT_HSYNC	H'00', HSYNC_TYPE_DRAW
		NOP
		NOP
		REPEAT_HSYNC	D'224', HSYNC_TYPE_DRAW
		NOP
		NOP
		REPEAT_HSYNC	H'0A', HSYNC_TYPE_CALIB
		GOTO		DRAW_DISPLAY
		
;Subroutine for waiting 10-micro-second		;0.25-micro*4-Clock*(2+8)-Cycle=10-micro
TIME10MICRO	NOP				;1-Cycle
		NOP				;1-Cycle
		NOP				;1-Cycle
		NOP				;1-Cycle
		NOP				;1-Cycle
		NOP				;1-Cycle
		RETURN				;2-Cycle  Total 8-Cycle
		
		END
